name: 'e2e'
on:
  push:
    branches:
      - next
  pull_request:
    branches:
      - next
jobs:
  e2e:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node_version: [16]
        include:
          - os: macos-latest
            node_version: 16
          - os: windows-latest
            node_version: 16
      fail-fast: false
    name: 'e2e: node-${{ matrix.node_version }}, ${{ matrix.os }}'
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 8

      - name: Set node version to ${{ matrix.node_version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}
          cache: 'pnpm'

      - run: pnpm install

      - name: Build
        run: npm run build:h5

      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          install: true
          start: npm run dev:ssr
          working-directory: ./packages/playground/ssr
          wait-on: 'http://localhost:5173'
          wait-on-timeout: 480
          browser: chrome
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
